version: '3'

volumes:
  mysql:
    driver: local

services:
  php-fpm:
    build: ./php-fpm
    volumes:
      - ../www:/var/www
    environment:
      - PHP_IDE_CONFIG=PHPSTORM
    expose:
      - "9000"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    links:
      - php-fpm
  mysql:
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080